name: 🚀 FTP Deploy (Test)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout kódu
        uses: actions/checkout@v3

      - name: 🚀 Deploy přes FTP (test bez secrets)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: tla01.vas-server.cz
          username: studenti
          password: Studenti_2025
          local-dir: ./build/
          server-dir: /kratoja/
